media:
  # Folder where your images live, relative to repo root
  input: _images
  # How those files are referenced in HTML, e.g. <img src="/_images/foo.png">
  output: /_images

settings:
  content:
    # Important so existing HTML isn’t blown away when you edit via CMS
    merge: true

content:
  # All top-level .html files in the repo root
  - name: pages
    label: Pages
    type: collection
    path: "."
    match: "*.html"

    # Optional: define which frontmatter/fields you actually want editable
    fields:
      - name: title
        label: Title
        type: string
        required: false

      - name: body
        label: Body
        type: rich-text
        required: false
